spring.application.name=BusinessManager
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=retail_db

# Server Port (React usually runs on 3000, so we keep Java on 8080)
server.port=9090

# Logging - Clean up console noise
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.com.business.manager=DEBUG